### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ldraind** [LW2904/maniac#46] opened 2020-05-26 04:31 UTC
Hi I am a windows10 user.
I'm asking because the program is not working properly.

C: \ Users \ ldrai \ Downloads \ maniac-master \ maniac-0.7.1> maniac-v0.7.1-win64-debug.exe
[debug] [src \ maniac.c: main] songs path is 'C: \ Users \ ldrai \ AppData \ Local \ osu! \ Songs \'
[debug] [src \ process.c: get_process_id] process ID for osu! .exe is 10088
[debug] [src \ game.c: do_setup] got handle to game process with ID 10088
[debug] [src \ maniac.c: standby] in standby mode
[debug] [src \ beatmap.c: find_partial_file] found file '228619 AKINO with bless4-EXTRA MAGIC HOUR'
[debug] [src \ beatmap.c: find_partial_file] found file '01 .mp3 '
[debug] [src \ beatmap.c: find_beatmap] C: \ Users \ ldrai \ AppData \ Local \ osu! \ Songs \ 228619 AKINO with bless4-EXTRA MAGIC HOUR \ 01 .mp3 is not a beatmap
[debug] [src \ beatmap.c: parse_beatmap] parsing beatmap 'C: \ Users \ ldrai \ AppData \ Local \ osu! \ Songs \ 228619 AKINO with bless4-EXTRA MAGIC HOUR \ 01 .mp3'
[debug] [src \ beatmap.c: parse_beatmap] beatmap version is 0
failed to parse beatmap ()
[debug] [src \ maniac.c: standby_loop] play returned status 0
an error occurred while playing, there's likely additional error output above

Is there any solution?
I am sorry that my bad english. thanks

**Comment by ldraind** [comment] 2020-05-26 04:36
I am using windows 10.
However, an error occurred during execution, so I ask a question.

C:\Users\ldrai\Downloads\maniac-master\maniac-0.7.1>maniac-v0.7.1-win64
parsing an unsupported beatmap (0)failed to parse beatmap ()
an error occurred while playing, there's likely additional error output above

C:\Users\ldrai\Downloads\maniac-master\maniac-0.7.1>maniac-v0.7.1-win64-debug
[debug] [src\maniac.c:main] songs path is 'C:\Users\ldrai\AppData\Local\osu!\Songs\'
[debug] [src\process.c:get_process_id] process ID for osu!.exe is 10460
[debug] [src\game.c:do_setup] got handle to game process with ID 10460
[debug] [src\maniac.c:standby] in standby mode
[debug] [src\beatmap.c:find_partial_file] found file 'Failed'
[debug] [src\beatmap.c:find_partial_file] found file '61604 Aoi Eir - INNOCENCE (TV Size).osz'
[debug] [src\beatmap.c:find_beatmap] C:\Users\ldrai\AppData\Local\osu!\Songs\Failed\61604 Aoi Eir - INNOCENCE (TV Size).osz is not a beatmap
[debug] [src\beatmap.c:parse_beatmap] parsing beatmap 'C:\Users\ldrai\AppData\Local\osu!\Songs\Failed\61604 Aoi Eir - INNOCENCE (TV Size).osz'
[debug] [src\beatmap.c:parse_beatmap] beatmap version is 0
parsing an unsupported beatmap (0)failed to parse beatmap ()
[debug] [src\maniac.c:standby_loop] play returned status 0
an error occurred while playing, there's likely additional error output above

Is there any way to solve it?
The program turns off after this error.
Sorry for the poor English. thanks you.

**Comment by LW2904** [comment] 2020-05-26 10:26
Duplicate of #38

**Closed** 2020-05-26 11:57 UTC
Labels: bug, duplicate
