### ISSUE TITLE
I have no clue what im doing

### ISSUE THREAD

**Issue by dissaprive** [LW2904/maniac#31] opened 2019-03-18 03:07 UTC
I cant get it to work at all. I don't know how to compile anything with MinGW, and Im generally just lost. Can you elaborate on how to get this working? Thanks.

**Comment by LW2904** [comment] 2020-04-18 11:09
Please see #32.

**Comment by dissaprive** [comment] 2020-04-19 11:43
When I run the .exe file, i cant configure anything, and the program doesn't really function. I know i have to complie it, but how would go about that.

Thank you for your help so far!

**Comment by LW2904** [comment] 2020-04-19 13:47
You don't have to compile it, I provide compiled binaries in the [release tab](https://github.com/LW2904/maniac/releases/tag/0.3.0).

Assuming you downloaded it to the default Downloads folder, you'd open `cmd` and do
```
cd Downloads
maniac-win64.exe
```

To options are passed at execution time so `maniac-win64.exe -h` shows the help screen and exits, while  `maniac-win64.exe -l 100 -r 10` starts maniac with an initial humanization level of 100 with a delta of 10.

**Comment by LW2904** [comment] 2020-04-19 13:51
It looks like map parsing is currently broken though, which probably has something to do with the latest release being 2 years ago.

I'll look into it in the coming days and ping you when and if I have a fix.

**Comment by dissaprive** [comment] 2020-04-20 15:52
When i try to run it, it says libwinthread-1.dll was not found.
Also, once again, thank you for your help

**Comment by LW2904** [comment] 2020-04-20 17:14
I just set up a Windows machine and I can reproduce the issue. Static builds are likely the solution (as they were back when someone first had this issue #20) so I'll just make them the default. Until I finally get around to rewriting everything, at least.

Not going to provide new builds for now since they wouldn't work anyways, but future ones shouldn't give you that error anymore.

And no need to thank me, I'm using this as an excuse to procrastinate so it's a win-win ;)

**Comment by dissaprive** [comment] 2020-04-20 18:41
When I run the static build, i cant change any of the settings in the prompt. All it says is that its parsing 6 points of a random map, and it doesn't work when i try to use it. I think im missing something, but idk what it is

**Comment by LW2904** [comment] 2020-04-21 13:10
Sounds like you're opening the executable like you would open a GUI application, i. e. by "double-clicking it".

Maniac is designed to be executed from a command line, so you have to (1) download the file, (2) open up a terminal (Windows key > type `cmd` > Enter), (3) navigate to the directory you downloaded it to (most likely the Downloads folder, so `cd Downloads` or alternatively `cd C:\Users\${your username}\Downloads`) and (4) execute it by typing the name of the file.

You can then provide options by appending the relevant switches (like `-h`, etc.) to the file name.

https://i.imgur.com/xqXF84w.png

**Comment by LW2904** [comment] 2020-04-21 13:14
I'm in the process of streamlining some internal background stuff and fixing up maniac to work with the most recent version of the game, once that's done I'll look into putting a proper usage guide in the README. I don't have much (read: any) experience with publishing applications like this for end-users so I apologise that this hasn't been done before.

**Comment by dissaprive** [comment] 2020-04-22 07:23
okay. Thank you!

**Comment by LW2904** [comment] 2020-04-22 15:39
The map parsing failure is now tracked in #33. Since the original question behind this issue was (hopefully) resolved I'll close it now. Feel free to follow the other issue to get notified when it's closed. If you still get the libwinthread error when running the [most recent release](https://github.com/LW2904/maniac/releases) please create a separate issue.

**Closed by LW2904** 2020-04-22 15:39 UTC
