### ISSUE TITLE
Column detection

### ISSUE THREAD

**Issue by Deathreus** [LW2904/maniac#39] opened 2020-04-27 03:58 UTC
Mania uses the X of objects to determine which column it goes down, they are a fixed distance apart (usually). during parsing of the hit objects you can sort the array by X position, then run through it and increment the column count for each higher value encountered.

As I have learned, this is not fullproof, some maps will occasionally not be uniform (typically older maps, which would have a compatible CircleSize property to determine columns anyway)

**Comment by LW2904** [comment] 2020-04-27 10:50
From what I've seen so far all maps which were created for osu!mania have their CircleSize set to the column count, this is confirmed by the [osu!lazer code](https://github.com/ppy/osu/blob/005a4928385c811f57d4a39cecc2a921eb2022e9/osu.Game.Rulesets.Mania/Beatmaps/ManiaBeatmapConverter.cs#L50) but not documented officially.  The linked file also contains a formula for calculating the column count if the beatmap isn't originally for mania.

In case you're arguing for non-mania map support: `maniac` doesn't support non-mania maps since their `HitPoints` section obviously follows another format and that'd require implementing (at least) something like [this](https://github.com/ppy/osu/blob/005a4928385c811f57d4a39cecc2a921eb2022e9/osu.Game.Rulesets.Mania/Beatmaps/ManiaBeatmapConverter.cs#L157) which I don't feel is worth the effort and complexity at the moment. Maybe when I get around to refactoring beatmap parsing as it's own standalone application.

**Comment by Deathreus** [comment] 2020-04-29 20:57
[This commit is correct](https://github.com/LW2904/maniac/commit/4e1842a59e2b83599385e7d32d6c95bba17daad9#diff-2ac285aac1635459a6f0f76e90f29fa3R244), maps circle size occasionally doesn't match how many columns there are

**Comment by LW2904** [comment] 2020-04-29 23:07
Well yes, as I said earlier, if (rather, iff) the beatmap was not originally created for mania (in osu!lazer terms this means if `!IsForCurrentRuleset`) then the circle size does not determine the column count. In cases where the beatmap _was_ originally created for mania circle size _does_ determine the column count. (As an aside, in case you referred to the comment in the commit you linked, that comment is wrong, that's why I removed it.)

Since I forgot to ask this in my earlier comment, what's the purpose of this issue? (Please don't take that in an offensive way, genuine question.)

**Comment by LW2904** [comment] 2020-06-02 20:45
Closing this as part of the 1.x cleanup.

**Closed by LW2904** 2020-06-02 20:45 UTC
