### ISSUE TITLE
I want to ask

### ISSUE THREAD

**Issue by ari4431** [LW2904/maniac#42] opened 2020-05-02 21:29 UTC
this program is automatically detect what beatmap we playing or we must put target dir beatmap that will be play?

**Comment by ari4431** [comment] 2020-05-02 21:41
![image](https://user-images.githubusercontent.com/64565799/80892944-4c69c680-8cf8-11ea-85f8-174ed2cd4a82.png)
oh sorry, automatically detect beatmap is ok, but why i get error unsupported beatmap?

**Comment by LW2904** [comment] 2020-05-03 13:09
Looks like the map finding algorithm choked, since it's trying to parse a MP3 file as a beatmap.

I'll look into it and get back to you, thanks for reporting!

**Comment by LW2904** [comment] 2020-05-03 23:32
This issue is more or less a duplicate of #38 so I'll close this for now. I made a note of this particular issue over there, you might want to follow the other issue since I'll post there once I have a fix.

**Closed by LW2904** 2020-05-03 23:32 UTC
Labels: bug
