### ISSUE TITLE
Couldn't parse beatmap

### ISSUE THREAD

**Issue by recreationx** [LW2904/maniac#28] opened 2018-10-22 13:54 UTC
C:\Users\zn\Downloads>maniac-win64-static-debug
[debug] [process.c:get_process_id] process ID for osu!.exe is 6784
[debug] [utils.c:do_setup] got handle to game process with ID 6784
[debug] [main.c:standby] in standby mode
[debug] [utils.c:find_partial_file] couldn't open directory C:\Users\User\AppData\Local\osu!\Songs\`WΩ\
[debug] [beatmap.c:find_beatmap] couldn't find beatmap in C:\Users\zn\AppData\Local\osu!\Songs\`WΩ\
[debug] [beatmap.c:parse_beatmap] couldn't open file C:\Users\zn\AppData\Local\osu!\Songs\`WΩ\
failed to parse beatmap (C:\Users\zn\AppData\Local\osu!\Songs\`WΩ\)
[debug] [main.c:standby_loop] play returned status 0
an error occured while playing, there's likely additional error output above

Running as adminstrator

**Comment by LW2904** [comment] 2018-10-22 13:58
Might be caused by the special characters in the file name, do other beatmaps work?

**Comment by LW2904** [comment] 2020-04-25 16:59
Okay nevermind, looks like beatmap finding choked since that path obviously doesn't exist. There's a good chance this was fixed offhandedly by now and if it's not I'm actively on the lookout for bugs again, so if you're still on the lookout for a mania cheat feel free to try again.

**Comment by LW2904** [comment] 2020-06-02 20:46
Closing this as part of the 1.x cleanup.

**Closed by LW2904** 2020-06-02 20:46 UTC
Labels: 0.x, bug
