### ISSUE TITLE
dll issie

### ISSUE THREAD

**Issue by dissaprive** [LW2904/maniac#35] opened 2020-04-22 19:02 UTC
Hello. even with the newest release of the executable, im still getting the libwinpthread-1.dll issue when i attempt to run the program

**Comment by dissaprive** [comment] 2020-04-23 11:45
okay, thank you

**Comment by LW2904** [comment] 2020-04-23 21:59
I just released v0.3.10 which should now have all dependencies statically linked, hopefully resolving this issue. I still can't reproduce the error but I'm currently downloading a VM image with a clean Windows which should help (it's a 20Gb download so it'll take a while).

If that _still_ doesn't fix the issue perhaps the hotfix in #34 can help as a temporary measure.

**Comment by dissaprive** [comment] 2020-04-23 23:35
![cmd_fNSry0Jn3c](https://user-images.githubusercontent.com/48664443/80159647-8cfb6e80-8599-11ea-8154-c44e0aee4e92.png)



Now Its runs, but i get this message

**Comment by LW2904** [comment] 2020-04-23 23:48
Alright cool, that's a start -- the map parsing failure is tracked in #33. Does the beatmap name in the console match what you actually started in osu?

Closing this since the original issue is now resolved, you can still reply though.

**Closed by LW2904** 2020-04-23 23:48 UTC
Labels: bug
