### ISSUE TITLE
Errors during compilation

### ISSUE THREAD

**Issue by ssCherry** [LW2904/maniac#14] opened 2018-08-21 14:46 UTC
![terminal2](https://user-images.githubusercontent.com/42537021/44408647-72bdf180-a569-11e8-801d-66033f650747.png)
When downloading the build-essential, an error occurs with 404 not found.
When apt-get update, an error [13:Permission denied]

**Comment by LW2904** [comment] 2018-08-21 14:49
These instructions only apply to Linux distributions using `apt`. It looks like you are running Windows, so you do not have to install anything beforehand.

**Comment by ssCherry** [comment] 2018-08-21 14:53
And what to do with the build-essential because of it as I understood it is not compiled?

**Comment by LW2904** [comment] 2018-08-21 14:57
No offense, but you understood wrongly, then. `build-essential` will install a number of utilities that are required for compilation _on Linux_. Even then, it is very likely that they are already present on the system.

Am I correct in assuming that you are running Windows 10? Which terminal emulator are you using, currently?

**Comment by ssCherry** [comment] 2018-08-21 14:59
Ubuntu 18.09

**Comment by LW2904** [comment] 2018-08-21 15:06
So you are using the Windows Subsystem for Linux? I've never tried, but I very (very) much doubt that you'll be able to run `maniac` from in there. Thinking about it, I can pretty much guarantee that you won't.

Use a shell like [Babun](https://babun.github.io/) or [Cmder](http://cmder.net/) to run `build.sh`.

**Comment by ssCherry** [comment] 2018-08-21 15:09
Well, i try it

**Comment by ssCherry** [comment] 2018-08-21 15:47
Babun: 
![babun](https://user-images.githubusercontent.com/42537021/44412894-a7827680-a572-11e8-8aca-2815d1a1004c.png)

**Comment by LW2904** [comment] 2018-08-21 17:32
My apologies, it appears that Babun cannot properly parse `build.sh`. I had wrongly assumed that it was able to do that based on previous experience with a different setup.

I don't usually work on my Windows machine, but when I do I use `Git Bash` which comes with Git, and can be downloaded [here](https://git-scm.com/downloads). Please make sure you have an up to date version of the repository since it is entirely possible that older versions might be broken on Windows (as I'm not always able to test on there).

**Comment by ssCherry** [comment] 2018-08-21 17:34
Okay

**Comment by ssCherry** [comment] 2018-08-21 17:47
:'(
![default](https://user-images.githubusercontent.com/42537021/44419275-66df2900-a583-11e8-9223-697e077919b2.png)

**Comment by LW2904** [comment] 2018-08-21 18:12
Can you try to run `gcc -v` anywhere in your terminal?

This is to confirm that GCC is installed and properly configured on your system. It should look something like this, if successful:
![](https://i.imgur.com/lG7SoV8.png)

**Comment by ssCherry** [comment] 2018-08-21 18:13
gcc not installed.

**Comment by LW2904** [comment] 2018-08-21 18:17
GCC should come as part of MinGW. Read the Getting Started guide, and also take note of the Environment Settings section.

**Comment by LW2904** [comment] 2018-08-21 18:19
In any case, I just published release 0.2.0 which you can download [here](https://github.com/LW2904/maniac/releases/tag/0.2.0).

**Comment by ssCherry** [comment] 2018-08-21 18:27
error to parse beatmap (( null )) This is because I have osu! not in the standard path?

**Comment by LW2904** [comment] 2018-08-21 18:33
That's very likely, yes. If you want support for custom osu! install locations, please create an issue and I'll see if I can implement it in a future version. Else, you could edit the `#define DEFAULT_OSU_PATH` line in `osu.h`, but note that the path defined there should be _relative to your home directory_.

**Comment by ssCherry** [comment] 2018-08-21 18:37
![default](https://user-images.githubusercontent.com/42537021/44421872-69914c80-a58a-11e8-8a0a-71ae3ff3ca58.png)

**Comment by LW2904** [comment] 2018-08-21 19:01
The issue with `INT_MAX` being undefined should be fixed with 2b41ebe1c3e37c8817824acc836f62225f2b03ff. I was not able to reproduce this issue on my machine, but I am reasonably sure I fixed the crux of the issue.

**Comment by ssCherry** [comment] 2018-08-21 19:09
![default](https://user-images.githubusercontent.com/42537021/44423496-e58d9380-a58e-11e8-80c6-6d24b0c684fc.png)

**Comment by LW2904** [comment] 2018-08-21 19:12
Are you on an x32 machine? And are you certain that you have the latest version of the repository? Currently, `check_chunk` (which is defined statically in `pattern.c`) is on line 20, not 21.

**Comment by ssCherry** [comment] 2018-08-21 19:14
x64 machine, my version of gcc is not similar to yours, probably because of this.

**Comment by ssCherry** [comment] 2018-08-21 20:12
can you compile a maniac with a path to osu! on drive C: ?

**Comment by LW2904** [comment] 2018-08-21 20:30
You'll want 8.1.0, x84_64 and POSIX threads. Be sure to update your PATH if necessary and make sure that `gcc -v` yields the correct version information.

**Comment by LW2904** [comment] 2018-08-21 20:38
If you want a quick fix, just copy your osu! directory to `C:\Users\Cherry\AppData\Local\`. Alternatively, you could always bypass the map searching by passing the `-m` option with a valid path to a beatmap. `scripts/find.js` should be helpful with that.

**Comment by ssCherry** [comment] 2018-08-21 20:43
Okay

**Comment by ssCherry** [comment] 2018-08-21 20:47
failed to parse beatmap (i change path)

**Comment by ssCherry** [comment] 2018-08-21 20:57
![error](https://user-images.githubusercontent.com/42537021/44428721-ee399600-a59d-11e8-8dc3-a8ea33ba0618.png)

**Comment by LW2904** [comment] 2018-08-22 18:04
I have just updated release 0.2.0 with `maniac-win64-debug.exe` which does not have any significant code changes but is compiled with some additional debug flags set. If you want to help me track down the issue(s) you are having, please run the build and let me know which messages you get.

This is how it looks like on my machine after having played a beatmap.

![](https://i.imgur.com/2myWmOW.png)

**Comment by ssCherry** [comment] 2018-08-22 18:06
okay

**Comment by ssCherry** [comment] 2018-08-22 18:12
Now there is no error, but it clamps the D key
![default](https://user-images.githubusercontent.com/42537021/44482056-11248280-a650-11e8-85eb-0453d07543f1.png)

**Comment by ssCherry** [comment] 2018-08-22 20:06
The result is the same.

**Comment by LW2904** [comment] 2018-08-22 21:30
I threw together a basic test suite that should cover most of `maniac`s basic functionality. It can be downloaded [here](https://file.io/XBmk5O) and I hope that it can shed some light on what's going wrong on your system.

At this point, I'm really just amazed at how many things can go wrong on a single machine, especially considering that it's running flawlessly for me.

**Comment by ssCherry** [comment] 2018-08-22 21:33
okay

**Comment by ssCherry** [comment] 2018-08-22 21:40
auto closing time to notice only the path found and PID process osu!

**Comment by ssCherry** [comment] 2018-08-22 21:48
error: failed to found beatmap

**Comment by ssCherry** [comment] 2018-08-23 19:17
l, like everything itself is fixed x)

**Comment by ssCherry** [comment] 2018-08-23 19:34
when I turn on more than 4 keys it breaks.

**Comment by ssCherry** [comment] 2018-08-23 19:55
That - works, then - no

**Comment by LW2904** [comment] 2018-08-23 19:57
The cheat does not currently support anything but 4k Maps, although support
for Xk should be trivial to implement at this point. As always - make an
issue and I'll look into it.

Good to see that you got maniac working after all, by the way, have fun.

**Comment by ssCherry** [comment] 2018-08-23 21:41
![default](https://user-images.githubusercontent.com/42537021/44553516-6935b480-a736-11e8-8d63-d9bc70488868.png)
oh,no

**Comment by LW2904** [comment] 2018-08-24 16:29
Could you upload one of the beatmaps which are not working for you somewhere, so I can take a look at them and do some testing on my machines?

**Comment by ssCherry** [comment] 2018-08-24 18:38
All maps do not work.

**Comment by LW2904** [comment] 2018-08-25 10:45
Since, at this point, this is a different problem with a (likely) very different cause, please create an issue and I'll look into it.

**Comment by LW2904** [comment] 2018-08-25 10:47
To get back to the original problem, have you been able to compile successfully by now?

**Comment by ssCherry** [comment] 2018-08-25 10:48
no

**Comment by LW2904** [comment] 2018-09-23 21:04
I am closing this issue since it has ventured far from the original problem. If you are still running into errors, please feel free to create an issue while making sure to __provide as many details as possible__.

**Closed by LW2904** 2018-09-23 21:04 UTC
Labels: bug
